/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120424-g03b9180fe3-20250731"
#endif /* AVUTIL_FFVERSION_H */
